import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProviderWrapper from "../components/ThemeProviderWrapper";
import HelmetProviderWrapper from "../components/HelmetProviderWrapper";
import Index from "../components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Dashboard | Team Interval",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <link
                    href="https://fonts.googleapis.com/css2?family=Public+Sans:wght@400;500;600;700&display=swap"
                    rel="stylesheet"
                />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0"
                />
            </head>
            <body className={inter.className}>
                <ThemeProviderWrapper>
                    <Index>
                        <HelmetProviderWrapper>
                            {children}
                        </HelmetProviderWrapper>
                    </Index>
                </ThemeProviderWrapper>
            </body>
        </html>
    );
}
